# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapAppReactNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapAppReactNative

  target 'MapAppReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'AppAuth', '>= 0.94'
