image: openjdk:8-jdk
variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  FLUTTER_VERSION: "https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.7.8+hotfix.4-stable.tar.xz"
  

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

  # android sdk setup
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail
  # flutter sdk setup
  - wget --output-document=flutter-sdk.tar.xz $FLUTTER_VERSION
  - tar -xf flutter-sdk.tar.xz
  - export PATH=$PATH:$PWD/flutter/bin
  - echo flutter.sdk=$PWD/flutter > android/local.properties
  - chmod +x ./android/gradlew
  # fluttercouch setup
  - pwd
  - rm -rf ../fluttercouch
  - git clone git://github.com/fluttercouch/fluttercouch.git ../fluttercouch
  - sed -i 's/~> 2.5.1/~> 2.6.3/g' ../fluttercouch/ios/fluttercouch.podspec

stages:
  - test
  - build

build:apk:
  only:
    - schedules
    - web
  stage: build
  script:
    - flutter build apk
    - flutter build web
  artifacts:
    paths:
      - build/app/outputs/apk/app.apk
      - build/web/
    expire_in: 1 day

# build:ios:
#   only:
#     - schedules
#     - web
#   stage: build
#   script:
#     - flutter build ios --no-codesign
#   artifacts:
#     paths:
#       - build/ios/iphoneos/Runner.app
#     expire_in: 1 day

test:flutter:
  stage: test
  script:
    - flutter test