# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
image: openjdk:8-jdk
variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  FLUTTER_VERSION: "https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v1.14.6-beta.tar.xz"


before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

  # android sdk setup
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail
  # flutter sdk setup
  - wget --output-document=flutter-sdk.tar.xz $FLUTTER_VERSION
  - tar -xf flutter-sdk.tar.xz
  - export PATH=$PATH:$PWD/flutter/bin
  - flutter channel beta
  - flutter upgrade
  - flutter config --enable-web
  - echo flutter.sdk=$PWD/flutter > android/local.properties
  - chmod +x ./android/gradlew
  # fluttercouch setup (incl. update the version via sed)
  - pwd
  - rm -rf ../fluttercouch
  - git clone git://github.com/fluttercouch/fluttercouch.git ../fluttercouch
  - sed -i 's/~> 2.5.1/~> 2.6.3/g' ../fluttercouch/ios/fluttercouch.podspec

stages:
  - test
  - build

test:flutter:
  stage: test
  script:
    - flutter test

build:apk:
  only:
    - schedules
    - web
  stage: build
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/app.apk
    expire_in: 1 day

# build:ios:
#   only:
#     - schedules
#     - web
#   stage: build
#   script:
#     - flutter build ios --no-codesign
#   artifacts:
#     paths:
#       - build/ios/iphoneos/Runner.app
#     expire_in: 1 day

build:web:
  only:
    - schedules
    - web
  stage: build
  script:
    - flutter build web
  artifacts:
    paths:
      - build/web/
    expire_in: 1 day

build:docker_web:
  variables:
    # use git tag, or git branch for docker image tag
    DOCKER_IMAGE_TAG: "${CI_COMMIT_TAG:-$CI_COMMIT_BRANCH}"
    # pass GitLab CI var as build arg
    MAPAPP_COMMIT_SHA: "$CI_COMMIT_SHA"
  image:
    name: docker/compose:1.24.0
    # unset `docker-compose` as default Entrypoint
    entrypoint: ['']
  stage: build
  before_script:
    - cp mapapp.env.default mapapp.env
    - echo "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME"
  script:
    - docker-compose build
  after_script:
    # todo: move to separate stage; use gitlab ci `only` syntax (and push to GitLab image registry to persist between stages)
    # only push docker images on master branch or tags
    - if [ "$CI_COMMIT_BRANCH" = master ] || [ "$CI_COMMIT_BRANCH" = develop ] || [ -n "$CI_COMMIT_TAG" ]; then docker-compose push; fi
