---
version: "3.4"
services:
  web:
    build:
      context: .
      args:
        # set build arg from env var with same name
        # add default to squelch warnings
        COMMIT_SHA: ${COMMIT_SHA:-local}
    image: "uwcirg/map-app-client:${DOCKER_IMAGE_TAG:-latest}"
    ports:
      - ${EXTERNAL_PORT:-8010}:${PORT:-80}
    env_file:
      - mapapp.env
